[package]
name = "memsonic"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
libm = "0.2.16"

[features]
default = []
desktop = []
ffi = []

[package.metadata.docs.rs]
all-features = true

[[test]]
name = "simpleflight"
path = "tests/simpleflight.rs"
required-features = ["desktop"]
