//! # builder
//!
//! Simulation builders construct sensor initial configurations based on
//! a set of input paramaters. Besides kinematic flight profile, paramaters
//! generated by the builder define the simulation.
//!
//! Similar to how sensors' evaluation pipeline is split between disperser
//! (artificial noise) and collector (subsequent filtering), a builder degrades
//! configurations for both parts separately, with "disperse" for noise and
//! "decay" for collector.

use crate::{
    Alignment, Bias, ODR,
    math::interpolate,
    math::{Barron, Blend, Hyperbolic, Randomize, SquareMatrix},
    sensors::{Collector, Disperser},
};
use core::f32::consts::FRAC_1_SQRT_2;

/// Builder public API.
pub trait SimBuilder {
    /// Initial input to the builder.
    type InputParams;

    /// Returns a new builder with specified output data rates
    /// and parameters to use in derivation. Please note that
    /// the ODR values passed here are not guaranteed to be
    /// used by the engine (see [`rate`] below).
    ///
    /// ## Examples
    ///
    /// ```ignore
    /// let b = SkewedIMU::new((10, 10, 30, 40), 0.25);
    /// let s = Simulation::<10>::new::<memsonic::env::BuffaloJuly>(b, 1000);
    /// ```
    fn new(r: ODR, p: Self::InputParams) -> Self;

    /// Returns configs for all three IMU sensors (accelerometer,
    /// gyroscope, magnetometer). Idempotent, but is usually not
    /// called by the user but instead inside the simulation.
    fn imu(&mut self) -> [SyntheticSensor<3>; 3];

    /// Returns a config for barometer. Idempotent, but is usually
    /// not called by the user but instead inside the simulation.
    fn baro(&mut self) -> SyntheticSensor<1>;

    /// Returns the engine's sampling rate. Sensor's ODRs should be always
    /// preserved unless the calculated ODR value is abnormal. In reality,
    /// though, there are no sensors running at 2^126 sps; otherwise, the
    /// simulation will never finish computing.
    fn rate(&mut self) -> f32;
}

/////////////////////////////////////////////////////////////////////////////
// Sensor configuration (user)
/////////////////////////////////////////////////////////////////////////////

/// A public wrapper around internal sensor configuration.
pub struct SyntheticSensor<const N: usize> {
    pub(crate) k: Collector,
    pub(crate) m: Disperser<N>,
    pub(crate) s: Option<f32>,
}

/// Public sensor configuration. Optional values set to `None`
/// will be replaced with a heuristic guess by the builder.
#[derive(Clone, Copy)]
pub struct SensorConf<const N: usize> {
    pub odr: f32,
    pub cutoff: f32,
    pub qbw: f32,
    pub sigma: f32,
    pub bias: Bias<N>,
    pub align: Alignment<N>,
    pub sens: Option<f32>,
}

impl<const N: usize> SensorConf<N> {
    /// Returns a uniform "ideal" preset, which is then modified
    /// by the builder to create the desired configuration.
    fn ideal(odr: f32) -> Self {
        Self {
            odr,
            cutoff: (odr * 0.4).min(100.0),
            qbw: FRAC_1_SQRT_2,
            sigma: 0.0,
            bias: [0.0; N],
            align: Alignment::identity(),
            sens: None,
        }
    }

    /// Transforms [`SensorConf`] into [`SyntheticSensor`].
    fn wrap(&self) -> SyntheticSensor<N> {
        SyntheticSensor {
            k: Collector {
                odr: self.odr,
                cutoff: self.cutoff,
                qbw: self.qbw,
            },
            m: Disperser {
                sigma: self.sigma,
                bias: self.bias,
                align: self.align,
            },
            s: self.sens,
        }
    }

    /// Degrades the collector (filtering step) configuration.
    ///
    /// Returns a unique reference to [`SensorConf`] for chaining
    /// other filters.
    fn decay(&mut self, b: impl Blend, x: f32) -> &mut Self {
        let i = 1.0 - x;

        let max_cutoff = (self.odr * 0.4).min(100.0);
        let min_cutoff = (self.odr * 0.1).min(20.0);

        self.cutoff = interpolate(b, max_cutoff, min_cutoff, i);
        self.qbw = interpolate(b, FRAC_1_SQRT_2, 0.5, i);

        self
    }

    /// Degrades the disperser (artificial noise step) configuration.
    ///
    /// Returns a unique reference to [`SensorConf`] for chaining
    /// other filters.
    fn disperse(&mut self, b: impl Blend, x: f32) -> &mut Self {
        self.sigma = interpolate(b, 0.1, 0.0005, x);
        self.bias = self.bias.randomize(x);
        self.align = self.align.randomize(x);
        self
    }
}

/////////////////////////////////////////////////////////////////////////////
// Builder implementations
/////////////////////////////////////////////////////////////////////////////

/// A builder that does not apply any filters and lets the user manually
/// set the values. It is a "parent object" which other builders use.
pub struct Manual {
    pub acc: SensorConf<3>,
    pub gyr: SensorConf<3>,
    pub mag: SensorConf<3>,
    pub bar: SensorConf<1>,
}

impl SimBuilder for Manual {
    type InputParams = ();

    /// Returns itself, with ideal sensor configurations.
    fn new(r: ODR, _p: Self::InputParams) -> Self {
        Self {
            acc: SensorConf::ideal(r.0),
            gyr: SensorConf::ideal(r.1),
            mag: SensorConf::ideal(r.2),
            bar: SensorConf::ideal(r.3),
        }
    }

    /// Returns the slowest viable rate (0.2 * minimum ODR).
    fn rate(&mut self) -> f32 {
        self.acc
            .odr
            .min(self.gyr.odr)
            .min(self.mag.odr)
            .min(self.bar.odr)
            / 5.0
    }

    /// Wraps IMU sensor configuration into internal type.
    fn imu(&mut self) -> [SyntheticSensor<3>; 3] {
        [self.acc.wrap(), self.gyr.wrap(), self.mag.wrap()]
    }

    /// Wraps barometer configuration into internal type.
    fn baro(&mut self) -> SyntheticSensor<1> {
        self.bar.wrap()
    }
}

/// A builder that degrades IMU configuration based on
/// a degradation factor d in [0, 1].
pub struct SkewedIMU {
    m: Manual,
    d: f32,
}

impl SimBuilder for SkewedIMU {
    type InputParams = f32;

    fn new(r: ODR, p: Self::InputParams) -> Self {
        Self {
            m: Manual::new(r, ()),
            d: p.clamp(0.0, 1.0),
        }
    }

    /// Returns the slowest viable rate (0.2 * minimum ODR).
    ///
    /// TODO: implement variations from the default.
    fn rate(&mut self) -> f32 {
        self.m.rate()
    }

    fn imu(&mut self) -> [SyntheticSensor<3>; 3] {
        let b = Barron::new((1.8, 0.4));

        self.m.acc.decay(b, self.d).disperse(b, self.d);
        self.m.gyr.decay(b, self.d).disperse(b, self.d);
        self.m.mag.decay(b, self.d).disperse(b, self.d);

        self.m.acc.sens = Some(0.0005 + 0.2 * self.d);
        self.m.gyr.sens = Some(0.00001 + 0.005 * self.d);

        self.m.imu()
    }

    fn baro(&mut self) -> SyntheticSensor<1> {
        let b = Hyperbolic::new(4.0);

        self.m
            .bar
            .decay(b, 0.05 * self.d)
            .disperse(b, 0.05 * self.d);

        self.m.baro()
    }
}
