//! # builder
//! 
//! Simulation builders construct sensor initial configurations based on
//! a set of input paramaters. Besides kinematic flight profile, paramaters
//! generated by the builder define the simulation.
//! 
//! Similar to how sensors' evaluation pipeline is split between disperser
//! (artificial noise) and collector (subsequent filtering), a builder degrades
//! configurations for both parts separately, with "disperse" for noise and
//! "decay" for collector.

use core::f32::consts::FRAC_1_SQRT_2;
use crate::{
	Alignment, Bias, ODR,
	math::{Blend, Hyperbolic, Randomize, SchilckBias, SquareMatrix},
	math::{ceil, interpolate},
	sensors::{Collector, Disperser}
};

/// Builder public API.
pub trait SimBuilder {
	/// Initial input to the builder.
	type InputParams;

	/// Returns a new builder with specified output data rates
	/// and parameters to use in derivation. Please note that
	/// the ODR values passed here are not guaranteed to be
	/// used by the engine (see [`rate`] below).
	/// 
	/// ## Examples
	/// 
	/// ```
	/// let b = SkewedIMU::new((10.0, 10.0, 15.0, 40.0), 0.25);
	/// let s = Simulation::<10>new(b, 1000);
	/// ```
	fn new(r: ODR, p: Self::InputParams) -> Self;

	/// Returns configs for all three IMU sensors (accelerometer,
	/// gyroscope, magnetometer). Idempotent, but is usually not
	/// called by the user but instead inside the simulation.
	fn imu(&mut self) -> [SyntheticSensor<3>; 3];

	/// Returns a config for barometer. Idempotent, but is usually
	/// not called by the user but instead inside the simulation.
	fn baro(&mut self) -> SyntheticSensor<1>;

	/// Returns the engine's sampling rate. Whether the sensors'
	/// ODRs will be preserved depends on the specific builder
	/// implementation.
	fn rate(&mut self) -> u32;
}

/////////////////////////////////////////////////////////////////////////////
// Sensor configuration (user)
/////////////////////////////////////////////////////////////////////////////

/// A public wrapper around internal sensor configuration.
pub struct SyntheticSensor<const N: usize> {
	pub(crate) k: Collector,
	pub(crate) m: Disperser<N>,
	pub(crate) s: Option<f32>
}

/// Public sensor configuration. Optional values set to `None`
/// will be replaced with a heuristic guess by the builder.
#[derive(Clone, Copy)]
pub struct SensorConf<const N: usize> {
	pub odr: u32,
	pub cutoff: f32,
	pub qbw: f32,
	pub firsens: Option<f32>,
	pub sigma: f32,
	pub bias: Bias<N>,
	pub align: Alignment<N>,
	pub sens: Option<f32>
}

impl<const N: usize> SensorConf<N> {
	/// Returns a uniform "ideal" preset, which is then modified
	/// by the builder to create the desired configuration.
	fn ideal(odr: u32) -> Self {
		Self {
			odr,
			cutoff: 100.0,
			qbw: FRAC_1_SQRT_2,
			firsens: None,
			sigma: 0.0,
			bias: [0.0; N],
			align: Alignment::identity(),
			sens: None
		}
	}

	/// Transforms [`SensorConf`] into [`SyntheticSensor`].
	fn wrap(&self) -> SyntheticSensor<N> {
		SyntheticSensor {
			k: Collector {
				odr: self.odr,
				cutoff: self.cutoff,
				qbw: self.qbw,
				sens: self.firsens.unwrap_or(
					(self.odr as f32 * 10_000.0)
					.clamp(10_000.0, 700_000.0)
				)
			},
			m: Disperser {
				sigma: self.sigma,
				bias: self.bias,
				align: self.align
			},
			s: self.sens
		}
	}

	/// Degrades the collector (filtering step) configuration.
	/// 
	/// Returns a unique reference to [`SensorConf`] for chaining
	/// other filters.
	fn decay<B: Blend>(&mut self, d: f32, k: f32) -> &mut Self {
		let i = 1.0 - d;
		
		self.cutoff = interpolate::<B>(100.0, 20.0, i, k);
		self.qbw = interpolate::<B>(FRAC_1_SQRT_2, 0.5, i, k);
		self.firsens = Some(interpolate::<B>(700_000.0, 5_000.0, i, k));
		self
	}
	
	/// Degrades the disperser (artificial noise step) configuration.
	/// 
	/// Returns a unique reference to [`SensorConf`] for chaining
	/// other filters.
	fn disperse<B: Blend>(&mut self, d: f32, k: f32) -> &mut Self {
		self.sigma = interpolate::<B>(0.1, 0.0005, d, k);
		self.bias = self.bias.randomize(d);
		self.align = self.align.randomize(d);
		self
	}
}

/////////////////////////////////////////////////////////////////////////////
// Builder implementations
/////////////////////////////////////////////////////////////////////////////

/// A builder that does not apply any filters and lets the user manually
/// set the values. It is a "parent object" which other builders use. 
pub struct Manual {
	pub acc: SensorConf<3>,
	pub gyr: SensorConf<3>,
	pub mag: SensorConf<3>,
	pub bar: SensorConf<1>,
}

impl SimBuilder for Manual {
	type InputParams = ();

	/// Returns itself, with ideal sensor configurations.
	fn new(r: ODR, _p: Self::InputParams) -> Self {
		Self {
			acc: SensorConf::ideal(r.0),
			gyr: SensorConf::ideal(r.1),
			mag: SensorConf::ideal(r.2),
			bar: SensorConf::ideal(r.3)
		}
	}

	/// Returns the engine's sampling rate with two upheld invariants:
	/// 
	/// 1. The returned rate is at least one (millisecond).
	/// 2. The returned rate is at least five times smaller than the
	///    fastest sensor's output data rate.
	/// 
	/// If these two invariants contradict, the engine's rate is set to
	/// 1 millisecond and sensors' ODRs are upscaled to preserve ratio
	/// and an optimal sampling rate.
	fn rate(&mut self) -> u32 {
		let m = self.acc.odr
			.min(self.gyr.odr)
			.min(self.mag.odr)
			.min(self.bar.odr);

		let mut eng = m / 5;

		if eng == 0 {
			eng = 1;
			let k = 5.0 / (m as f32);

			self.acc.odr = ceil(self.acc.odr as f32 * k) as u32;
			self.gyr.odr = ceil(self.gyr.odr as f32 * k) as u32;
			self.mag.odr = ceil(self.mag.odr as f32 * k) as u32;
			self.bar.odr = ceil(self.bar.odr as f32 * k) as u32;
		}

		eng
	}

	/// Wraps IMU sensor configuration into internal type.
	fn imu(&mut self) -> [SyntheticSensor<3>; 3] {
		[
			self.acc.wrap(),
			self.gyr.wrap(),
			self.mag.wrap()
		]
	}

	/// Wraps barometer configuration into internal type.
	fn baro(&mut self) -> SyntheticSensor<1> {
		self.bar.wrap()
	}
}

/// A builder that degrades IMU configuration based on
/// a degradation factor d in [0, 1].
pub struct SkewedIMU {
	m: Manual,
	d: f32
}

impl SimBuilder for SkewedIMU {
	type InputParams = f32;

	fn new(r: ODR, p: Self::InputParams) -> Self {
		Self {
			m: Manual::new(r, ()),
			d: p.clamp(0.0, 1.0)
		}
	}

	/// Returns the engine's sampling rate with two upheld invariants:
	/// 
	/// 1. The returned rate is at least one (millisecond).
	/// 2. The returned rate is at least five times smaller than the
	///    fastest sensor's output data rate.
	/// 
	/// If these two invariants contradict, the engine's rate is set to
	/// 1 millisecond and sensors' ODRs are upscaled to preserve ratio
	/// and an optimal sampling rate.
	fn rate(&mut self) -> u32 {
		self.m.rate()
	}

	fn imu(&mut self) -> [SyntheticSensor<3>; 3] {
		self.m.acc
			.decay::<SchilckBias>(self.d, 0.5)
			.disperse::<SchilckBias>(self.d, 0.5);
		self.m.gyr
			.decay::<SchilckBias>(self.d, 0.5)
			.disperse::<SchilckBias>(self.d, 0.5);
		self.m.mag
			.decay::<SchilckBias>(self.d, 0.5)
			.disperse::<SchilckBias>(self.d, 0.5);

		self.m.acc.sens = Some(0.0005 + 0.2 * self.d);
		self.m.gyr.sens = Some(0.00001 + 0.005 * self.d);

		self.m.imu()
	}

	fn baro(&mut self) -> SyntheticSensor<1> {
		self.m.bar
			.decay::<Hyperbolic>(0.05 * self.d, 0.05)
			.disperse::<Hyperbolic>(0.05 * self.d, 0.05);

		self.m.baro()
	}
}